name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.9.6
      uses: actions/setup-python@v4
      with:
        python-version: "3.9.6"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Build executable with cx_Freeze
      run: |
        python setup.py build
        
    - name: Upload Package
      uses: actions/upload-artifact@v4
      with:
        name: Clive Webhook
        path: build/
